language: node_js
node_js:
- '6'
- '8'
- '9'
- '10'
- '11'
- '12'
before_script:
- npm install
deploy:
  provider: npm
  email: niklasvh@gmail.com
  api_key:
    secure: kvImHO/MsHoMJkZRpc641OlIc2QLdcCl07+q48F4pdwE5WfikiZ2MvGvpMoqP5gpsz0FEBkszOop4doiC3U5ZP64UDCRX34OADLX2hNYlZsmkYo5jI2MatJGB0E4YhnhXXctol4hrIFYUwPPfHXvYncwCw0wg9KSGtLgxzvugpk=
  on:
    tags: true
    branch: master
    repo: niklasvh/base64-arraybuffer
